apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["./integrationtests.test"]
      restartPolicy: Never
  backoffLimit: 4