name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit Tests
      run: make test-docker
    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.10.0"
    - name: Integration Tests
      run: make ci-integration-tests